version: 2.1
description: Circle CI
orbs:
  node: circleci/node@4.2.0
jobs:
  test_library:
    executor:
      name: node/default
      tag: '15.10'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: CHROME_BIN=/usr/bin/google-chrome && npm run test:lib:ci
workflows:
  test_my_app:
    jobs:
      - test_library